<a href="https://colab.research.google.com/github/bakudbilla/Hamoye_internship/blob/main/Intro_ML_with_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [5]:
#Creating a  numpy array
a=[1,2,3,4]
print(type(a))
#to make it a numpy array;
b=np.array(a)
print(type(b))

<class 'list'>
<class 'numpy.ndarray'>


In [9]:
#to print shape of array
print(b.shape)
#to print the dimensions
print(b.ndim)


(4,)
1


In [14]:
b= np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)
print(b.ndim)
print(b.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int64


In [17]:
#generating random numbers
np.random.random((2,3))
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [23]:
#indexing
b[0,2]

3